version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    command: sh -c "yarn start"
    ports:
      - 8000:8000
    volumes:
      - './app:/app'
    environment:
      - LANG=C.UTF-8
      - PYTHONIOENCODING=utf8
      - ENV=development
      - COMMIT_SHA1=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DATABASE_CREATION=create_preset_data
    depends_on:
      - db
    tty: true
  db:
    image: mysql:8.0
    platform: linux/amd64
    command: >-
      mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql-mode='TRADITIONAL,NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY'
      --max_connections=10000
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  bundle:
    driver: local
  data:
    driver: local
  socket:
    driver: local
